---
name: CodeCov
description: "Reports testing coverage for the repository"

runs:
  using: composite
  steps:
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.out
        flags: unittests
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
